# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/router/main/router/pkg/config/config.schema.json

# Cosmo Router full configuration example
# See https://cosmo-docs.wundergraph.com/router/configuration for details

version: "1"

# General router options
dev_mode: true
log_level: "debug"
listen_addr: "0.0.0.0:3002"
playground_enabled: true
playground_path: "/"
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 15s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "/app/config.json"

headers:
  all:
    request:
      - op: "propagate"
        named: "apikey"

cors:
  allow_methods:
    - "POST"
    - "OPTIONS"
  allow_origins:
    - "https://cosmo.wundergraph.com"
  allow_headers:
    - "apikey"
    - "X-WG-TRACE"
  allow_credentials: false